### PR TITLE
feat(update_user): deprecate update in favor of upsert

### PR DESCRIPTION
**Pull request by peterdeme**

### CODE REVIEW

**Comment by ferhatelmas** [comment]
too many colons

**Review by ferhatelmas — APPROVED** [review]
we could update tests too but good to keep as is to exercise old code

**Comment by peterdeme** [comment]
@ferhatelmas yeah my idea was to update the tests once we fully retire the old methods

**Comment by ferhatelmas** [comment]
> @ferhatelmas yeah my idea was to update the tests once we fully retire the old methods

agreed ⚡

**Pull request merged**
