### PR TITLE
Add response handler to client

### PR DESCRIPTION
**Pull request by betterwithranch**
# Submit a pull request

## CLA

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [x] The code changes follow best practices
- [x] Code changes are tested (add some information if not applicable)

## Description of the pull request

Suggestion for providing access to rate limit response headers as mentioned in #18

### CODE REVIEW

**Comment by tbarbugli** [comment]
perhaps I missed something but I think this approach would not work if the client is shared by different threads/procs (ie unicorn pre-fork approach) @Bogdan-D

**Comment by betterwithranch** [comment]
@tbarbugli  I just tested this and it does preserve a proc assigned to an instance variable after forking in unicorn.  I believe only file descriptors, sockets, etc. need to be reset when the process is forked.

It is up to the consumer to ensure that their proc is thread-safe if it is being shared across unicorn workers, but that is true of anything they are doing in their app.

**Comment by tbarbugli** [comment]
@betterwithranch perhaps it would be safer if we made client.on_response private (so that you can only attach your callback when the client is constructed).

How do you plan to use this on your application? I can imagine this approach works really well if you want to collect headers to logging/metrics infrastructure.

**Comment by betterwithranch** [comment]
@tbarbugli yes, that's exactly how I'm planning to use it.  I like the idea of passing it to the constructor and making it private.  Maybe we could even narrow the scope more and name it something explictly for this purpose.  If we do that, we could pass the values of the rate limit headers instead of the full headers array so the specific headers would be encapsulated in the library.  A method with the signature ```capture_metrics(limit, remaining, reset_time)``` maybe?

**Comment by betterwithranch** [comment]
Just realized that these headers don't indicate which rate these values apply to.  Since it's a callback, I need some context in order to know what metric to apply it to.

**Comment by tbarbugli** [comment]
> Just realized that these headers don't indicate which rate these values apply to. Since it's a callback, I need some context in order to know what metric to apply it to.

that sounds an easy one to fix since you have all of that in the same scope ;)

**Comment by betterwithranch** [comment]
Solved this by subclassing `StreamChat::Client` and overriding `track_response` to include tracking rate limits found in response headers.

``` ruby
module ChatService
  class ApiClient < ::StreamChat::Client
    private

    def parse_response(response)
      Endpoint.track_rate_limit(response)
      super
    end
  end
end
```

**Pull request closed without merging**
